
#XML related

CONTAINS='CONTAINS'
XMLVAR='VAR'
EMPTY_CONTAINER='EMPTY_CONTAINER'
XML_NONE='NONE'
XML_ANY='ANY'
XML_PRODUCT='PRODUCT'
XML_GIVE='GIVE'
XML_GET='GET'
XML_RULE='RULE'
XML_PATH='PATH'

# Input Header Names
VERSION="VER"
PICKS="bom_items"
PART_NUMBER='pn'
DATE='date_as_string'
CUST='CUST'
PATTERNID='PATTERN'

BLACK_PALMHIVE='99'
LABEL="LABEL"
BORDERCOLOUR="BOARDERCOLOUR"
DESCSHEET="descriptions"
PRODIDSHEET="production_id"
SQSHEET='part_of_sequence'
QTYSHEET='quantity'
SIZE_SHEET='size'


# ERRORS 

NOT_FOUND="Product not found"
CUSTOM_SIZE_ERROR="This code is used to define custom sizes please check actual size required"
NO_SIZE_ERROR='Product requires a valid size'
FILE_OPEN="File is open in another program please close and try again"
LOST_CHILD='Cant Find part of this product'
NO_PICK="couldn't Pick"
XML_ERROR='SPEX PRODUCTS.xml file Failed to load check tags are consistant'
NOTVALID="Product not Valid"
CUSTVARERROR="Cant Retrieve Custom Variables "
QTY_ERROR="invalid Quantity"
CSV_ERROR="unable to open CSV"
NOT_IN_SAVE_CSV='Cant Find Product in save file it might have been moved'
FAILED_MOVE="could not move to destination Product will not be cut"
EXPORT_ERRORS=" jobs contain errors"
NOT_FOUND_ODOO_IMPORT="could not retrieve job(s)"

#messages 

FOLDERS_CREATED='Folders have been Created'

# ID number related
IDINCREMENT=2
ID_MULIPLIER=.01
#PRODUCT VARS

SIZE='SIZE'
CODE='CODE'
SQ='seqNum'
QTY='QTY'
PICK='PICK'
FIRST='FIRST'
SECOND='SECOND'
THIRD='THIRD'
FORTH='FORTH'
WIDTH='WIDTH'
DEPTH='DEPTH'
HEIGHT='HEIGHT'
DH='DH' # depth or height depending product type.
NONE='NONE'
IDCHILDREN="IDCHILDREN"
ID="ID"
NOTES='notes'
ERRORS='ERRORS'
PARENTCODE='PARENT' # used to define parent products that hold the actual products export will ignore
LAYERALBLE='LAYERALBLE'
STATUS='STATUS'
SOLOPARENT='SOLOPARENT'
BIN_GROUP='BINGROUP'
BIN="BIN"
INTSQ="INTSQ" #faux varable created on request by product.getVar
FAUX_CODE='FAUX_CODE'
ALLERRORS='ALLERRORS'
INNERPATTERN='INNERPATTERN'
INNERPATTERNB="INNERPATTERNB"
INNERPATTERNR='INNERPATTERNR'
INCONTPATTERN='INCONTPATTERN'
FOAMPATTERN='FOAMPATTERN'
TOTAL_STATUS='TOTALSTATUS'
PSPATTERN='PSPATTERN'
ERROR_PATTERN="ERROR"
LL1="LL1"
LL2="LL2"
LL3="LL3"
LL4="LL4"
LL5="LL5"
STAR="*"
LL1D="1:"
LL2D="2:"
LL3D="3:"
LL4D="4:"
LL5D="5:"
LL5D="6:"
LABELLAYER="LABELS"
INOTE='INOTE'
INTERAL="(IN)"
ADDED="(ADDED)"
USERMATCHED="UM"
ALTCODES="ALTCODES"
# PART PATHNAMES

DATAFOLDER="DATA"
RAWCSVPATH="RAWRELEASE.csv"
OUTPUTCSV="_SAVE_FILE.CSV"
NOTCUTCSV="NOTCUT.CSV"

RELEASESUBFOLDERS=['FABRIC',"CUSHION FOAM",'ACCESSORIES','BACKREST FOAM','SNOOOOOOZE']
WORKFLOWCSV="_ORDER_FILE.CSV"
RELEASESAVEFOLDER="Releases_save_folder"
CSVSUFFIX=r'/*.csv'
SAVEHEADERCSV="SAVE_HEARDERS.csv"
EXPORT_HEADER_CSV="EXPORT_HEADERS.csv"
LAYERED_PATTERN_SUFFIX="-2L"
EXTRAS_CSV_SUFFIX = 'EXTRAS.csv'
GBR_SUFFIX_NO_DOT='gbr'

NOTCUTHEADER=['PARENT PART NUMBER','SEQUENCE NUMBER','SIZE','CHILD','REASON']  # not in use
CSV_HEADERS=["quantity","colour","notes","descriptions","pn","part_of_sequence","date_as_string","size","production_id","prefix","bom_items","link","Suffix","CUST","VER"] #not in use
JOB_VEIW_HIDDEN_VARS=[FIRST,SECOND,THIRD,FORTH,IDCHILDREN,CODE,DH,SIZE_SHEET,DESCSHEET,INNERPATTERN,INNERPATTERNB,INNERPATTERNR,FOAMPATTERN,INCONTPATTERN,PSPATTERN,ALTCODES]
INGNORE_WHEN_MATCHING=[ID,IDCHILDREN,DESCSHEET,SQ,NOTES,ERRORS,LABEL,QTY,ALTCODES]
IGNORE_ON_EXPORT=[SOLOPARENT,BIN_GROUP,DESCSHEET,INNERPATTERN,INNERPATTERNB,INNERPATTERNR,FOAMPATTERN,INCONTPATTERN,NOTES,ERRORS,ALTCODES]

#BINS

MAX_BIN_SIZE=12
MIN_BIN_SIZE=6

#statuses 

CUTTING='CUTTING'
LAYERED='LAYERED'
PICK='PICK'
MOVED='MOVED'
MULTI_SQ='MULTI'

#Groups 

PROD_CREATE_OPTIONAL=[PICKS,DATE,CUST,NOTES,DESCSHEET,PRODIDSHEET]
PROD_CREATE_REQUIRED=[(PART_NUMBER,CODE),(SQSHEET,SQ),(QTYSHEET,QTY),(SIZE_SHEET,SIZE)]
IGNORE_WHEN_ADDING_UM=[LABEL,SQ,QTY,ERRORS,NOTES,PARENTCODE,INOTE,PATTERNID,BORDERCOLOUR]

